name: CI

on:
  push:
    branches:
      - master
      - feature/*
  release:
    types: [published]

env:
  ZEIT_NOW_SCOPE: ${{ secrets.ZEIT_NOW_SCOPE }}
  ZEIT_NOW_TOKEN: ${{ secrets.ZEIT_NOW_TOKEN }}

jobs:
  deploy_preview:
    name: "Deploy Preview"
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          npx now --scope "$ZEIT_NOW_SCOPE" --token "$ZEIT_NOW_TOKEN" --confirm --no-clipboard

  deploy_prod:
    name: "Deploy to Production"
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: |
          npx now --scope "$ZEIT_NOW_SCOPE" --token "$ZEIT_NOW_TOKEN" --prod --confirm --no-clipboard
