name: CI

on:
  push:
    branches:
      - master
      - feature/*
  release:
    types: [published]

env:
  VERCEL_SCOPE: ${{ secrets.ZEIT_NOW_SCOPE }}
  VERCEL_TOKEN: ${{ secrets.ZEIT_NOW_TOKEN }}
  NODE_VERSION: 16

jobs:
  deploy_preview:
    name: "Deploy Preview"
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
      - run: |
          npx vercel --scope "$VERCEL_SCOPE" --token "$VERCEL_TOKEN" --confirm --no-clipboard

  deploy_prod:
    name: "Deploy to Production"
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: $NODE_VERSION
      - run: |
          npx vercel --scope "$VERCEL_SCOPE" --token "$VERCEL_TOKEN" --prod --confirm --no-clipboard
